### ISSUE TITLE
What part of the .plist is the key?

### ISSUE THREAD

**Issue by JomSpoons** [m4fn3/pvr_decrypter#1]
Hello! I am having trouble decrypting my .pvr.ccz even though I have the .plist file. What part of this file is the key?

![image](https://github.com/user-attachments/assets/31ed93cd-d364-41b0-94fe-58486c3ed824)

I tried all the values in `smartupdate` but they did not work. I would appreciate any help. Thank you!

**Comment by m4fn3** [comment]
The key is not there. There is no point in encrypting resources if the key can be found there.

**Comment by JomSpoons** [comment]
I see, my mistake. I saw someone elsewhere saying the .plist contains the key. Thank you for clearing that up.
